window.examData =
	{
		columns: 
			[
				{ title: "Initiating" },
				{ title: "Planning" },
				{ title: "Executing" },
				{ title: "Monitoring & Controlling" },
				{ title: "Closing" }
			],

		rows:
			[
				{ title: " " }
			],

		items:
			[
                { title: "Select project manager", col: 0, row: 0, order: 0 },
                { title: "Determine company culture and existing systems", col: 0, row: 0, order: 1 },
                { title: "Collect processes, procedures and historical information", col: 0, row: 0, order: 2 },
                { title: "Divide large projects into phases", col: 0, row: 0, order: 3 },
                { title: "Understand the business case", col: 0, row: 0, order: 4 },
                { title: "Uncover initial requirements, assumptions, risks, constraints, and existing agreements", col: 0, row: 0, order: 5 },
                { title: "Access project and product feasibility withing the given constraints", col: 0, row: 0, order: 6 },
                { title: "Create measurable objectives", col: 0, row: 0, order: 7 },
                { title: "Develop project charter", col: 0, row: 0, order: 8 },
                { title: "Identify stakeholders and determine their expectations, influence and impact", col: 0, row: 0, order: 9 },

                { title: "Determing how you will plan for each knowledge area", col: 1, row: 0, order: 0 },
                { title: "Determine detailed requirements", col: 1, row: 0, order: 1 },
                { title: "Create project scope statement", col: 1, row: 0, order: 2 },
                { title: "Access what to purchase and create procurement documents", col: 1, row: 0, order: 3 },
                { title: "Determine planning team", col: 1, row: 0, order: 4 },
                { title: "Create WBS and WBS dictionary", col: 1, row: 0, order: 5 },
                { title: "Create activity list", col: 1, row: 0, order: 6 },
                { title: "Create network diagram", col: 1, row: 0, order: 7 },
                { title: "Estimate resource requirements", col: 1, row: 0, order: 8 },
                { title: "Estimate time and cost", col: 1, row: 0, order: 9 },
                { title: "Determine critical path", col: 1, row: 0, order: 10 },
                { title: "Develop schedule", col: 1, row: 0, order: 11 },
                { title: "Develop budget", col: 1, row: 0, order: 12 },
                { title: "Determine quality standards, processes and metrics", col: 1, row: 0, order: 13 },
                { title: "Create process improvement plan", col: 1, row: 0, order: 14 },
                { title: "Determine all roles and responsibilities", col: 1, row: 0, order: 15 },
                { title: "Plan communications and stakeholder engagement", col: 1, row: 0, order: 16 },
                { title: "Perform risk identification, qualitative and quantitative risk analysis, and risk response planning", col: 1, row: 0, order: 17 },
                { title: "Go back - iterations", col: 1, row: 0, order: 18 },
                { title: "Finalize procurement documents", col: 1, row: 0, order: 19 },
                { title: "Create change management plan", col: 1, row: 0, order: 20 },
                { title: 'Finalize the "how to execute and control" parts of all management plans', col: 1, row: 0, order: 21 },
                { title: "Develop realistic and final PM plan and performance measurement baseline", col: 1, row: 0, order: 22 },
                { title: "Gain formal approval of the plan", col: 1, row: 0, order: 23 },
                { title: "Hold kickoff meeting", col: 1, row: 0, order: 24 },
                
                { title: "Execute the work according to the PM plan", col: 2, row: 0, order: 0 },
                { title: "Produce product deliverables (product scope)", col: 2, row: 0, order: 1 },
                { title: "Gather work performance data", col: 2, row: 0, order: 2 },
                { title: "Request changes", col: 2, row: 0, order: 3 },
                { title: "Implement only approved changes", col: 2, row: 0, order: 4 },
                { title: "Continuously improve", col: 2, row: 0, order: 5 },
                { title: "Follow processes", col: 2, row: 0, order: 6 },
                { title: "Determine whether processes are correct and effective (quality assurance)", col: 2, row: 0, order: 7 },
                { title: "Perform quality audits", col: 2, row: 0, order: 8 },
                { title: "Acquire final team", col: 2, row: 0, order: 9 },
                { title: "Manager people", col: 2, row: 0, order: 10 },
                { title: "Evaluate team and individual performance", col: 2, row: 0, order: 11 },
                { title: "Hold team-building activities", col: 2, row: 0, order: 12 },
                { title: "Give recognition and rewards", col: 2, row: 0, order: 13 },
                { title: "Use issue logs", col: 2, row: 0, order: 14 },
                { title: "Facilitate conflict resolution", col: 2, row: 0, order: 15 },
                { title: "Release resources as work is completed", col: 2, row: 0, order: 16 },
                { title: "Send and receive information, and solicit feedback", col: 2, row: 0, order: 17 },
                { title: "Report on project performance", col: 2, row: 0, order: 18 },
                { title: "Manage stakeholder engagement and expectations", col: 2, row: 0, order: 19 },
                { title: "Hold meetings", col: 2, row: 0, order: 20 },
                { title: "Select sellers", col: 2, row: 0, order: 21 },

                { title: "Take action to control the project", col: 3, row: 0, order: 0 },
                { title: "Measure performance against the performance measurement baseline", col: 3, row: 0, order: 1 },
                { title: "Measure performance against other metrics in the PM plan", col: 3, row: 0, order: 2 },
                { title: "Analyze and evaluate performance", col: 3, row: 0, order: 3 },
                { title: "Determine if variances warrant a corrective action or other change request", col: 3, row: 0, order: 4 },
                { title: "Influence the factors that cause changes", col: 3, row: 0, order: 5 },
                { title: "Request changes", col: 3, row: 0, order: 6 },
                { title: "Perform integrated change control", col: 3, row: 0, order: 7 },
                { title: "Approve or reject changes", col: 3, row: 0, order: 8 },
                { title: "Update the PM plan and project documents", col: 3, row: 0, order: 9 },
                { title: "Inform stakeholders of the results of change requests", col: 3, row: 0, order: 10 },
                { title: "Monitor stakeholder engagement", col: 3, row: 0, order: 11 },
                { title: "Manager configuration", col: 3, row: 0, order: 12 },
                { title: "Create forecasts", col: 3, row: 0, order: 13 },
                { title: "Gain acceptance of interim deliverables from the customer", col: 3, row: 0, order: 14 },
                { title: "Perform quality control", col: 3, row: 0, order: 15 },
                { title: "Perform risk reassesments and audits", col: 3, row: 0, order: 16 },
                { title: "Manage reserves", col: 3, row: 0, order: 17 },
                { title: "Control procurements", col: 3, row: 0, order: 18 },

                { title: "Confirm work is done to requirements", col: 4, row: 0, order: 0 },
                { title: "Complete procurement closure", col: 4, row: 0, order: 1 },
                { title: "Gain final acceptance of the product", col: 4, row: 0, order: 2 },
                { title: "Complete financial closure", col: 4, row: 0, order: 3 },
                { title: "Hand off completed product", col: 4, row: 0, order: 4 },
                { title: "Solicit feedback from the customer about the project", col: 4, row: 0, order: 5 },
                { title: "Complete final performance reporting", col: 4, row: 0, order: 6 },
                { title: "Index and archive records", col: 4, row: 0, order: 7 },
                { title: "Gather final lessons learned and update knowledge base", col: 4, row: 0, order: 8 }
			]
	};
